sonar.projectKey=sureshsonardemo-jpg_q_r_code_scanner
sonar.organization=sureshsonardemo-jpg


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=q_r_code_scanner
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
